import Head from 'next/head'
import Image from 'next/image'
import Layout from "../sections/Layout"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Blog Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Layout>
          {/* Hero section */}
          <section className="flex flex-col items-center justify-center mt-12 space-y-10 sm:mt-24 md:mt-32">
             {/* Headlines */}
             <div className="max-w-4xl mx-auto space-y-4 text-center">
              <h1 className="text-4xl font-bold capitalize sm:text-7xl">
                <span className="block">An example blogging platform </span>
                <span className="block">for whoever you want</span>
              </h1>
              <h2 className="text-xl font-medium sm:text-2xl">
                Start your blog, share ideas, and connect with other people in the blogging community!
              </h2>
             </div>
             {/* CTA */}
             <button type="button" onClick={null} className="px-6 py-3 text-lg text-white bg-blue-600 border-2 border-blue-600 rounded-md hover:bg-blue-700 hover:border-blue-700 sm:text-xl focus:outline-none focus:ring-4 focus:ring-blue-600 focus:ring-opacity-50 whitespace-nowrap">

                Start your blog for free

              </button>
          </section>
        </Layout>
      
    </div>
  )
}
